pipeline {
    agent {
        docker {
            image 'node:latest'
            args "-p 3000:3000 --network host"
        }
    }
    
    stages {
        stage('Build') {
            steps {
                sh 'npm config set proxy=http://proxy:3128'
                sh 'npm config set http-proxy=http://proxy:3128'
                sh 'npm config set https-proxy=http://proxy:3128'
                sh 'npm config set https_proxy=http://proxy:3128'
                sh 'npm set timeout=16000000'
                sh 'git config --global http.proxy http://proxy:3128'
                sh 'git config --global https.proxy http://proxy:3128'
                sh 'npm config set strict-ssl false'
                sh 'npm config set registry http://registry.npmjs.org'
                sh 'npm cache clean --force'
                sh 'ls'
                sh 'npm install --verbose'
                
                                     
                }
            
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
