pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 3000:3000 --dns 10.0.0.2 --dns 8.8.8.8 --network host'
        }
    }
    environment {
        CI = 'true'
        HTTP_PROXY = 'http://proxy:3128'
        HTTPS_PROXY = 'http://proxy:3128'
        http_proxy = 'http://proxy:3128'
        https_proxy = 'http://proxy:3128'
        no_proxy = 'docker'
        NO_PROXY = 'docker'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
